### ISSUE TITLE
Clarify VLC dependency instructions

### ISSUE THREAD

**Issue by DBraun** [remap/YoutubeTOP#1]
I'm interested in having 64-bit support and audio output, so I was trying to build a new dll. What should I do with the folder "vlc-2.2.4"? I have a feeling I should put the contents of "vlc-2.2.4/include" and  "vlc-2.2.4/bin" somewhere.

**Comment by flowb** [comment]
Hi,

I'm interested in a 64-bit port as well. I'm trying to figure out the best way to compile a 64-bit version of libVlc but I'm getting a bit lost in the VLC documentation tree.
